name := "btop"
packages := "
btop
rocm-smi
"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/kinoite-main:41
"

import '../sysext.just'

all: default
