name := "steam-devices"
packages := "steam-devices"
enable_repos := "rpmfusion-nonfree-steam"
arch := "i686"
base_images := "
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/kinoite-main:41
"

import '../sysext.just'

all: default
