name := "steam"
packages := "steam"
enable_repos := "rpmfusion-nonfree-steam"
arch := "noarch i686 x86_64"
base_images := "
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/kinoite-main:41
"

import '../sysext.just'

all: default
